[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
tts = { git = "https://github.com/ChaoticOnyx/OnyxBay14.Drivers", package = "tts" }
pci = { git = "https://github.com/ChaoticOnyx/OnyxBay14.Drivers", package = "pci" }
riscv = "0.10.1"
riscv-rt = "0.11.0"
